### ISSUE TITLE
bash: /c/Users/gmaca/AppData/Local/Microsoft/WindowsApps/python3: Permission denied

### ISSUE THREAD

**Issue by gmacario** [gmacario/spaceappschallenge-2019#6]
See below

```
gmaca@DESKTOP-4P2TSAL MINGW64 ~/Documents/github/gmacario/spaceappschallenge-2019/site (master)
$ python3
bash: /c/Users/gmaca/AppData/Local/Microsoft/WindowsApps/python3: Permission denied

gmaca@DESKTOP-4P2TSAL MINGW64 ~/Documents/github/gmacario/spaceappschallenge-2019/site (master)
$
```

**Comment by meltz** [comment]
@gmacario , thank you so much, it solve my issue. 
Been pulling my hair out .......

**Comment by xtyi1997** [comment]
如果是中文的，window中左下角，搜索“管理应用执行别名“，即可关闭
![image](https://user-images.githubusercontent.com/28750869/78541009-8d6cd900-7827-11ea-8ccb-9f558ab65e08.png)

**Comment by Clarechioma** [comment]
after disabling both i got this 
AppData/Local/Microsoft/WindowsApps/python3: No such file or directory

**Comment by mkmor** [comment]
I got the same error "No such file or directory" when disabling the App execution aliases. Is there a way to change the Path to be the actual program file path?

**Comment by crashlamp** [comment]
Same here, I get `AppData/Local/Microsoft/WindowsApps/python: No such file or directory` after disabling the execution aliases.

**Comment by SaiYogananda** [comment]
first download python and anaconda
1) open git bash terminal
2) Enter cd . In case you get an error message here, such as bash: cd: command not found, you may need to uninstall Git and reinstall Git.
3) enter pwd and you should get the path as /c/Users/Username
example: /c/Users/Pawan
4) enter ls . This should print all the file names in your home directory.See for Anaconda3.
Go to that directory.So full path will be /c/Users/Pawan/Anaconda3

Enter the below steps in sequence

5) echo 'export PATH="$PATH:[YOUR_PATH]:[YOUR_PATH]/Scripts"' >> .bashrc
ex: echo 'export PATH="$PATH:/c/Users/Pawan/Anaconda3:/c/Users/Pawan/Anaconda3/Scripts"' >> .bashrc
6) echo 'alias python="winpty python.exe"' >> .bashrc
7) source .bashrc

check your conda version by typing
  conda --version

check your python version by
python --version 

if you get permission denied now then go to
![image](https://user-images.githubusercontent.com/40533641/82323587-e7031e80-99f5-11ea-9304-957ba2a5b20f.png)

Now enter python --version in your git bash terminal without  closing or restarting it.
 You will get your python version.

**Comment by mkmor** [comment]
@SaiYogananda Thank you very much! This worked!

**Comment by V-Curtis** [comment]
@SaiYogananda Im growing back the hair i lost on this!

**Comment by icnewer** [comment]
just type "PY" rather than "python", it works for me, just don't know why though.

**Comment by RitikPandey25** [comment]
> first download python and anaconda
> 
> 1. open git bash terminal
> 2. Enter cd . In case you get an error message here, such as bash: cd: command not found, you may need to uninstall Git and reinstall Git.
> 3. enter pwd and you should get the path as /c/Users/Username
>    example: /c/Users/Pawan
> 4. enter ls . This should print all the file names in your home directory.See for Anaconda3.
>    Go to that directory.So full path will be /c/Users/Pawan/Anaconda3
> 
> Enter the below steps in sequence
> 
> 1. echo 'export PATH="$PATH:[YOUR_PATH]:[YOUR_PATH]/Scripts"' >> .bashrc
>    ex: echo 'export PATH="$PATH:/c/Users/Pawan/Anaconda3:/c/Users/Pawan/Anaconda3/Scripts"' >> .bashrc
> 2. echo 'alias python="winpty python.exe"' >> .bashrc
> 3. source .bashrc
> 
> check your conda version by typing
> conda --version
> 
> check your python version by
> python --version
> 
> if you get permission denied now then go to
> ![image](https://user-images.githubusercontent.com/40533641/82323587-e7031e80-99f5-11ea-9304-957ba2a5b20f.png)
> 
> Now enter python --version in your git bash terminal without closing or restarting it.
> You will get your python version.

What do you mean YOUR_PATH?

**Comment by RitikPandey25** [comment]
> first download python and anaconda
> 
> 1. open git bash terminal
> 2. Enter cd . In case you get an error message here, such as bash: cd: command not found, you may need to uninstall Git and reinstall Git.
> 3. enter pwd and you should get the path as /c/Users/Username
>    example: /c/Users/Pawan
> 4. enter ls . This should print all the file names in your home directory.See for Anaconda3.
>    Go to that directory.So full path will be /c/Users/Pawan/Anaconda3
> 
> Enter the below steps in sequence
> 
> 1. echo 'export PATH="$PATH:[YOUR_PATH]:[YOUR_PATH]/Scripts"' >> .bashrc
>    ex: echo 'export PATH="$PATH:/c/Users/Pawan/Anaconda3:/c/Users/Pawan/Anaconda3/Scripts"' >> .bashrc
> 2. echo 'alias python="winpty python.exe"' >> .bashrc
> 3. source .bashrc
> 
> check your conda version by typing
> conda --version
> 
> check your python version by
> python --version
> 
> if you get permission denied now then go to
> ![image](https://user-images.githubusercontent.com/40533641/82323587-e7031e80-99f5-11ea-9304-957ba2a5b20f.png)
> 
> Now enter python --version in your git bash terminal without closing or restarting it.
> You will get your python version.

source .bashrc I am getting the error:'source' is not recognized as an internal or external command,
operable program or batch file.

**Comment by tuttoaposto** [comment]
@SaiYogananda This is genius! Thanks a lot!

**Comment by mrp100461** [comment]
i am getting this after changing manage app execution bash: /c/Users/mr_pe/AppData/Local/Microsoft/WindowsApps/python3: No such file or 
directory
**I got the fix just type py instead of python3 and all works fine**

**Comment by Emanoid** [comment]
> just type "PY" rather than "python", it works for me, just don't know why though.

I cannot begin  to appreciate you enough for this. I've spent hrs trying recommendations and yours worked instantly!!

**Comment by mrp100461** [comment]
I did the same, I got the answer from Python owns sites 😊

Yours

 



Mark Pearson


Work: 07939224113


Email:  ***@***.***> ***@***.***


 <http://www.linkedin.com/pub/mark-pearson/8/129/6b7> 


See who we know in common <http://www.linkedin.com/e/wwk/24194731/>

**Comment by katharinepires** [comment]
> just type "PY" rather than "python", it works for me, just don't know why though.

that's really worked to me too

**Comment by asolab** [comment]
better still, before you install do make sure you check the "ADD PYTHON TO PATH" box, then use command "winpty python" to run, it works

**Comment by UzmaMajeed52** [comment]
I got the same error after turning off the app installers. %UserProfile%/AppData/Local/Microsoft/WindowsApps/python3: No such file or directory
but after some time I saw a 'Play' button  on the top right side of the app, I clicked and my program ran.

**Comment by codeyourwayup** [comment]
works very well

**Comment by xincognitodev** [comment]
> i am getting this after changing manage app execution bash: /c/Users/mr_pe/AppData/Local/Microsoft/WindowsApps/python3: No such file or directory **I got the fix just type py instead of python3 and all works fine**

This Works!!
